<a href="https://colab.research.google.com/github/Harsh-COE/ML/blob/main/102003192.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
A=np.array([1,2,3,4]);
print(A.ndim);
print(A.shape);
print(A.size);
print(A.dtype);
print(A.itemsize);
print(A.data);

1
(4,)
4
int64
8


In [ ]:
import numpy as np
A=np.arange(2,10,dtype=float);
B=np.arange(2,3,0.1);
print(B);
# print(A);

[2.  2.1 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9]


In [ ]:
import numpy as np
A=np.linspace(1.,4.,6);
print(A);

[1.  1.6 2.2 2.8 3.4 4. ]


In [ ]:
import numpy as np
# A=np.eye(3);
A=np.eye(3,5,k=1);
print(A);

[[0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]]


In [ ]:
import numpy as np
# A=np.diag([1,2,3]);
A=np.array([[1,2],[3,4]]);
print(np.diag(A,k=0));

[1 4]


In [ ]:
import numpy as np
np.vander([1,2,3,4],3)

array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [16,  4,  1]])

In [ ]:

total = 0

list1 = [11, 5, 17, 18, 23]
for ele in range(0, len(list1)):
	total = total + list1[ele]

print("Sum of all elements in given list: ", total)


In [ ]:

list1 = [10, 20, 4, 45, 99]

list1.sort()


print("Largest element is:", list1[-1])

In [ ]:
a = (1, 11, 2)
x = sorted(a)
print(x)

In [ ]:
l = [1, 2, 4, 2, 1, 4, 5]
print("Original List: ", l)
res = [*set(l)]
print("List after removing duplicate elements: ", res)


In [ ]:
def long_words(n, str):
    word_len = []
    txt = str.split(" ")
    for x in txt:
        if len(x) > n:
            word_len.append(x)
    return word_len	
print(long_words(3, "The quick brown fox jumps over the lazy dog"))

In [ ]:
li1 = [10, 15, 20, 25, 30, 35, 40]
li2 = [25, 40, 35]

temp3 = []
for element in li1:
	if element not in li2:
		temp3.append(element)

print(temp3)


In [ ]:
dict = {'key1': 'hey', 'key2': 'fill_me'}
print("Current Dict is: ", dict)

dict['key2'] = 'hi'
dict['key3'] = 'world'
print("Updated Dict is:", dict)


In [ ]:
d1={1:10,2:20}
d2={3:30,4:40}
d3={5:50,6:60}
d1.update(d2)
d1.update(d3)
print("Concatenated dictionary is:")
print(d1)

In [ ]:

test_dict = {"Arushi": 22, "Mani": 21, "Haritha": 21}
del test_dict['Mani']

print("The dictionary after remove is : ", test_dict)




In [1]:

d = {
	'value1': 5,
	'value2': 4,
	'value3': 3,
	'value4': 2,
	'value5': 1,
}


answer = 1

for i in d:
	answer = answer*d[i]


print(answer)


120
